# Generated by Django 5.0.6 on 2024-06-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
    ]
