# Generated by Django 5.0.6 on 2024-07-15 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Billing',
                'db_table': 'Billing',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1', models.CharField(max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Shipping',
                'db_table': 'Shipping',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('time_created', models.TimeField(auto_now_add=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_paying_customer', models.BooleanField(default=False)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('woocommerce_id', models.IntegerField()),
                ('customerbiling_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='ecommerce.billingaddress')),
                ('customershipping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='ecommerce.shippingaddress')),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'Customer',
                'default_permissions': (),
            },
        ),
    ]
