# Generated by Django 5.0.6 on 2024-06-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_itemcategory_woocommerce_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
    ]
