# Generated by Django 5.0.6 on 2024-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_billingaddress_shippingaddress_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(max_length=250),
        ),
    ]
