# Generated by Django 5.0.6 on 2024-07-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_tags_woocommerce_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembrand',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemfamily',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specs',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
    ]
