# Generated by Django 5.0.6 on 2024-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_itembrand_woocommerce_id_itemfamily_woocommerce_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeasurment',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variationsdetail',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='variationsheader',
            name='woocommerce_id',
            field=models.IntegerField(default=0),
        ),
    ]
