# Generated by Django 5.0.6 on 2024-07-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='woocommerce_id',
            field=models.IntegerField(null=True),
        ),
    ]
