# Generated by Django 5.0.6 on 2024-07-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_unitofmeasurment_woocommerce_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variationsdetail',
            options={'verbose_name': 'variations_detail'},
        ),
    ]
