# Generated by Django 5.0.6 on 2024-07-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_variationsdetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variationsdetail',
            options={'default_permissions': (), 'verbose_name': 'variations_detail'},
        ),
    ]
