# Generated by Django 5.0.6 on 2024-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_order_currency_alter_order_woocommerce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasurment',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
