# Generated by Django 5.0.6 on 2024-07-01 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_variationsdetail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='parentt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='ecommerce.itemcategory'),
        ),
    ]
