# Generated by Django 5.0.6 on 2024-07-18 11:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_unitofmeasurment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasurment',
            name='type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('length', 'length'), ('width', 'width'), ('height', 'height'), ('weight', 'weight')], max_length=10), blank=True, default=None, null=True, size=None),
        ),
    ]
