# Generated by Django 5.0.6 on 2024-07-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='woocommerce_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
